// @generated by protobuf-ts 2.9.6
// @generated from protobuf file "example.proto" (package "example", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { TodoService } from "./example";
import type { TodoId } from "./example";
import type { TodoList } from "./example";
import type { Empty } from "./example";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { Todo } from "./example";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service example.TodoService
 */
export interface ITodoServiceClient {
    /**
     * @generated from protobuf rpc: AddTodo(example.Todo) returns (example.Todo);
     */
    addTodo(input: Todo, options?: RpcOptions): UnaryCall<Todo, Todo>;
    /**
     * @generated from protobuf rpc: GetTodos(example.Empty) returns (example.TodoList);
     */
    getTodos(input: Empty, options?: RpcOptions): UnaryCall<Empty, TodoList>;
    /**
     * @generated from protobuf rpc: DeleteTodo(example.TodoId) returns (example.Empty);
     */
    deleteTodo(input: TodoId, options?: RpcOptions): UnaryCall<TodoId, Empty>;
    /**
     * @generated from protobuf rpc: UpdateTodo(example.Todo) returns (example.Todo);
     */
    updateTodo(input: Todo, options?: RpcOptions): UnaryCall<Todo, Todo>;
}
/**
 * @generated from protobuf service example.TodoService
 */
export class TodoServiceClient implements ITodoServiceClient, ServiceInfo {
    typeName = TodoService.typeName;
    methods = TodoService.methods;
    options = TodoService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: AddTodo(example.Todo) returns (example.Todo);
     */
    addTodo(input: Todo, options?: RpcOptions): UnaryCall<Todo, Todo> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<Todo, Todo>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: GetTodos(example.Empty) returns (example.TodoList);
     */
    getTodos(input: Empty, options?: RpcOptions): UnaryCall<Empty, TodoList> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<Empty, TodoList>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: DeleteTodo(example.TodoId) returns (example.Empty);
     */
    deleteTodo(input: TodoId, options?: RpcOptions): UnaryCall<TodoId, Empty> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<TodoId, Empty>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateTodo(example.Todo) returns (example.Todo);
     */
    updateTodo(input: Todo, options?: RpcOptions): UnaryCall<Todo, Todo> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<Todo, Todo>("unary", this._transport, method, opt, input);
    }
}
