// @generated by protobuf-ts 2.9.4
// @generated from protobuf file "example.proto" (package "example", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { HealthCheckService } from "./example";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { HealthCheckReply } from "./example";
import type { HealthCheckRequest } from "./example";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service example.HealthCheckService
 */
export interface IHealthCheckServiceClient {
    /**
     * @generated from protobuf rpc: CheckHealth(example.HealthCheckRequest) returns (example.HealthCheckReply);
     */
    checkHealth(input: HealthCheckRequest, options?: RpcOptions): UnaryCall<HealthCheckRequest, HealthCheckReply>;
}
/**
 * @generated from protobuf service example.HealthCheckService
 */
export class HealthCheckServiceClient implements IHealthCheckServiceClient, ServiceInfo {
    typeName = HealthCheckService.typeName;
    methods = HealthCheckService.methods;
    options = HealthCheckService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: CheckHealth(example.HealthCheckRequest) returns (example.HealthCheckReply);
     */
    checkHealth(input: HealthCheckRequest, options?: RpcOptions): UnaryCall<HealthCheckRequest, HealthCheckReply> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<HealthCheckRequest, HealthCheckReply>("unary", this._transport, method, opt, input);
    }
}
